---
# Variabili comuni per tutti gli host

# Dominio e credenziali
rancher_domain: "ansible.app.iac-svil.almaviva.it"
rancher_password: "DanielE9233???"

# Versioni software
helm_version: "v3.11.0"
rancher_version: "2.11.2"

# Configurazione disco
vg_name: "vg_rancher"
lv_name: "lv_rancher"
rancher_mount_point: "/var/lib/rancher"
filesystem_type: "xfs"
mount_options: "defaults,noatime"

# Certificati
fullchain_pem_file: "fullchain.pem"
privkey_pem_file: "privkey.pem"
cacerts_pem_file: "cacerts.pem"
remote_cert_path: "/root"

# Cluster configuration
cluster_name: "iacdevops"
cluster_k8s_version: "v1.31.11+rke2r1"
cluster_cni: "canal"
ansibleSshHost: "localhost"

# Master node configuration (per kubectl setup sui new_managers)
master_node_ip: "10.205.166.216"
master_node_user: "root"
# master_node_name usa rancher_domain (evita duplicazioni)
# NFS VARS ####

# NFS VARS ####
# NFS VARS ####
nfsHostname: "nfs-server-01"
IPTargetHost: "10.205.166.219"

# Directory NFS
export_dir: "/share"
backup_dir: "backup"
k8s_dir: "k8s"

# Vecchie variabili (per compatibilità)
IPClientNFS1: "10.205.166.216"
IPClientNFS2: "10.205.166.218"
IPClientNFS3: "10.205.166.217"
IPClientNFS5: "10.205.166.214" 
IPClientNFS8: "10.205.166.215"

# Nuova lista client NFS (versione consigliata)
nfs_clients:
  - "10.205.166.216"  # cornelio.app.iac-svil.almaviva.it (master)
  - "10.205.166.218"  # rke2-worker1 (worker)
  - "10.205.166.214"  # rke2-worker2 (worker)
  - "10.205.166.217"  # rke2-manager2 (new_manager)
  - "10.205.166.215"  # rke2-worker3 

# Variabili blocco Rancher
nginx_server_name: "test.app.iac-svil.almaviva.it"
nginx_ssl_cert_path: "/etc/nginx/cert/fullchain.pem"
nginx_ssl_key_path: "/etc/nginx/cert/privkey.pem"

# Variabili blocco Multi-Servizi
multi_services_server_names:
  - "kibana.app.iac-svil.almaviva.it"
  - "grafana.app.iac-svil.almaviva.it"
  - "prometheus.app.iac-svil.almaviva.it"
  - "harbor.app.iac-svil.almaviva.it"
  - "pgadmin.app.iac-svil.almaviva.it"
  - "kafkaui.app.iac-svil.almaviva.it"

multi_services_ssl_cert_path: "/etc/nginx/cert/fullchain.pem"
multi_services_ssl_key_path: "/etc/nginx/cert/privkey.pem"

# Upstream servers
rancher_servers_https:
  - server: "10.205.166.216:443"
    max_fails: 3
    fail_timeout: "5s"


rancher_ingress_https:
  - server: "10.205.166.218:443"
    max_fails: 3
    fail_timeout: "5s"

rancher_ingress_https_1:
  - server: "10.205.166.214:443"
    max_fails: 3
    fail_timeout: "5s"

rancher_ingress_https_2:
  - server: "10.205.166.215:443"
    max_fails: 3
    fail_timeout: "5s"


# Configurazione Nginx
nginx_user: "www-data"
nginx_worker_processes: 2
nginx_worker_rlimit_nofile: 40000
nginx_client_max_body_size: "2G"

# Path directory certificati
nginx_cert_dir: "/etc/nginx/cert"

# Path locali certificati
local_ssl_cert_path: "files/fullchain.pem"
local_ssl_key_path: "files/privkey.pem"

# Storage Class Name (variabile globale)
storage_class_name: "nfs-k8s"

# Prometheus/Monitoring configuration
prometheus_namespace: "monitoring"
grafana_password: "SecureGrafanaPassword123!"  # CAMBIA QUESTA PASSWORD
prometheus_retention: "15d"
prometheus_storage_size: "5Gi"
grafana_storage_size: "3Gi"
alertmanager_storage_size: "2Gi"

# Ingress configuration
prometheus_create_ingress: true
grafana_domain: "grafana.app.iac-svil.almaviva.it"
prometheus_domain: "prometheus.app.iac-svil.almaviva.it"

# Resource configurations (optional overrides)
prometheus_cpu_requests: "1000m"
prometheus_memory_requests: "2Gi"
prometheus_cpu_limits: "2000m"
prometheus_memory_limits: "4Gi"

# Timeout configurations
helm_timeout: "15m"
pod_wait_timeout: "5m"  # Ridotto per evitare blocchi lunghi
